config/routes.rb
Rails.application.routes.draw do
  
  post 'proposals/:id' => 'proposals#update'
  get 'proposals/by_code/:code' => 'proposals#by_code'
  resources :proposals do
    member do
      post 'pay_with_stripe'
      post 'add_students'
    end
    collection do
      get 'search'
    end
  end

end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/preregistration.rb
class Preregistration < ActiveRecord::Base
	belongs_to :proposal
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
	belongs_to :full_plan, class_name: "Plan", foreign_key: :plan 
	belongs_to :full_currency, class_name: "Currency", foreign_key: :currency
	has_many :preregistrations

	def pay_with_stripe stripe_token, proposal
		setup_stripe
		currency = self.full_currency.code
		amount = (currency == 'COP' ? self.total_price : self.total_price * 100)
		begin
		  charge = Stripe::Charge.create(
		    :amount => amount.to_i, 
		    :currency => currency,
		    :source => stripe_token,
		    :description => "Pago de proposal: #{self.proposal_code}"
		  )
		  puts charge["id"]
		  self.is_paid = true
		  self.client_name = proposal.client_name
		  self.client_email = proposal.client_email
		  self.save
		rescue => e
		  self.is_paid = false
		 end
		self
	end

	def self.search query
		proposals = Proposal.where('client_email LIKE ? OR client_name LIKE ?', "%#{query}%", "%#{query}%").includes(:full_currency)
	end

	private

	def setup_stripe
		require "stripe"
		Stripe.api_key = "sk_test_6ATow9skSqZs6oIFAnDDCAmQ"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]
  before_action :set_default_reponse

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all.includes(:full_currency)
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @proposals = Proposal.search(params[:query])
    render :index
  end

  def by_code
    @proposal = Proposal.find_by_proposal_code(params[:code])
    render :show
  end

  def pay_with_stripe
    prop = Proposal.find(params[:id])
    @proposal = prop.pay_with_stripe params[:stripe_token], Proposal.new(proposal_params)
  end

  def add_students
    @proposal = Proposal.find(params[:id])
    pres = params[:students]
    pres.each do |student|
      st = Preregistration.new(student_name: student["student_name"], student_email: student["student_email"])
      @proposal.preregistrations << st
    end
    render :show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:user_id, :plan, :currency, :unit_price, :total_price, :proposal_code, :num_subscriptions, :num_months, :client_name, :client_email, :company_name, :company_details, :expiration_date, :notes, :is_paid, :payment_id)
      
    end

    def set_default_reponse
      request.format = :json
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PruebaPagos</title>
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/proposals/_form.html.erb
<%= form_for(@proposal) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proposal.errors.count, "error") %> prohibited this proposal from being saved:</h2>

      <ul>
      <% @proposal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :plan %><br>
    <%= f.number_field :plan %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.number_field :currency %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :proposal_code %><br>
    <%= f.text_field :proposal_code %>
  </div>
  <div class="field">
    <%= f.label :num_subscriptions %><br>
    <%= f.number_field :num_subscriptions %>
  </div>
  <div class="field">
    <%= f.label :num_months %><br>
    <%= f.number_field :num_months %>
  </div>
  <div class="field">
    <%= f.label :client_name %><br>
    <%= f.text_field :client_name %>
  </div>
  <div class="field">
    <%= f.label :client_email %><br>
    <%= f.text_field :client_email %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :company_details %><br>
    <%= f.text_area :company_details %>
  </div>
  <div class="field">
    <%= f.label :expiration_date %><br>
    <%= f.date_select :expiration_date %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :is_paid %><br>
    <%= f.check_box :is_paid %>
  </div>
  <div class="field">
    <%= f.label :payment_id %><br>
    <%= f.number_field :payment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing Proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Proposals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Plan</th>
      <th>Currency</th>
      <th>Unit price</th>
      <th>Total price</th>
      <th>Proposal code</th>
      <th>Num subscriptions</th>
      <th>Num months</th>
      <th>Client name</th>
      <th>Client email</th>
      <th>Company name</th>
      <th>Company details</th>
      <th>Expiration date</th>
      <th>Notes</th>
      <th>Is paid</th>
      <th>Payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.user_id %></td>
        <td><%= proposal.plan %></td>
        <td><%= proposal.currency %></td>
        <td><%= proposal.unit_price %></td>
        <td><%= proposal.total_price %></td>
        <td><%= proposal.proposal_code %></td>
        <td><%= proposal.num_subscriptions %></td>
        <td><%= proposal.num_months %></td>
        <td><%= proposal.client_name %></td>
        <td><%= proposal.client_email %></td>
        <td><%= proposal.company_name %></td>
        <td><%= proposal.company_details %></td>
        <td><%= proposal.expiration_date %></td>
        <td><%= proposal.notes %></td>
        <td><%= proposal.is_paid %></td>
        <td><%= proposal.payment_id %></td>
        <td><%= link_to 'Show', proposal %></td>
        <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
        <td><%= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposal', new_proposal_path %>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @proposal.user_id %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @proposal.plan %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @proposal.currency %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @proposal.unit_price %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @proposal.total_price %>
</p>

<p>
  <strong>Proposal code:</strong>
  <%= @proposal.proposal_code %>
</p>

<p>
  <strong>Num subscriptions:</strong>
  <%= @proposal.num_subscriptions %>
</p>

<p>
  <strong>Num months:</strong>
  <%= @proposal.num_months %>
</p>

<p>
  <strong>Client name:</strong>
  <%= @proposal.client_name %>
</p>

<p>
  <strong>Client email:</strong>
  <%= @proposal.client_email %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @proposal.company_name %>
</p>

<p>
  <strong>Company details:</strong>
  <%= @proposal.company_details %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%= @proposal.expiration_date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @proposal.notes %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @proposal.is_paid %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @proposal.payment_id %>
</p>

<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>